### PR TITLE
Fiew updates: begin() method and SkipROM support

### PR DESCRIPTION
**Pull request by hitech95**
Added:

- begin() method

- SkipROM support

Modified:

- Write now need the array size

Fixed:

- Now the write manage the power off of the data bus
- If CRC error on writing is detected another attempt is done

### CODE REVIEW

**Comment by tommag** [comment]
Thanks for contributing, this looks really good and a lot more Arduino-esque !

I don't think I deserve a copyright for the SkipROM example you wrote, would you mind using your name instead ? And maybe add it to LICENSE and the source code as well if you want.

**Comment by hitech95** [comment]
Hi,
I have updated with some copyrights.

Please take a look at this: [How can I add my library to Library Manager?](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-add-my-library-to-library-manager)

**Comment by tommag** [comment]
Thanks ! Merging.

**Comment by hitech95** [comment]
Thanks to you for the initial library!
You saved me lots of time to understand the datasheet, some parts was easier to understand via code!

If your curious I'm working on this:
https://hackaday.io/project/159654-fcthermostat-another-overengeneered-iot-device

Have a nice day :)

**Pull request merged**
